from .handle_delete_operation import handle_delete_product_operation
from .handle_read_operation import handle_read_operation
from .handle_write_operation import handle_write_new_product_operation
from .handle_update_operation import handle_update_product_operation

__all__ = ["handle_delete_product_operation", "handle_read_operation", "handle_write_new_product_operation", "handle_update_product_operation"]